# Generated by Django 3.1.3 on 2020-11-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_no', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(blank=True, max_length=128, null=True)),
                ('post_content', models.CharField(blank=True, max_length=1028, null=True)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_dt', models.DateTimeField(blank=True, null=True)),
                ('mod_dt', models.DateTimeField(blank=True, null=True)),
                ('post_image', models.TextField(blank=True, null=True)),
                ('post_image_size', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('reg_dt', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('weather', models.CharField(blank=True, max_length=45, null=True)),
                ('fashion', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_no', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('user_password', models.CharField(blank=True, max_length=45, null=True)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('user_nicknm', models.CharField(blank=True, max_length=45, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('user_sex', models.CharField(blank=True, max_length=45, null=True)),
                ('user_tel', models.CharField(blank=True, max_length=45, null=True)),
                ('user_address', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
